import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Terms of Service — WAYFARE",
  description: "Terms and conditions for using the WAYFARE travel planning platform.",
  robots: { index: true, follow: true },
};

const LAST_UPDATED = "September 2026";
const CONTACT_EMAIL = "hello@wayfaredun.netlify.app";

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col bg-background dark:bg-[#131313] transition-colors">
      <Navbar onOpenLogin={() => {}} />

      <main className="flex-1 w-full max-w-3xl mx-auto px-6 pt-32 pb-20">
        <div className="mb-10">
          <span className="font-sans text-xs uppercase tracking-widest text-secondary dark:text-[#1E8C80] font-semibold block mb-3">
            Legal Document
          </span>
          <h1 className="font-serif text-4xl sm:text-5xl text-on-surface dark:text-[#FAF7F2] font-normal leading-tight mb-4">
            Terms of Service
          </h1>
          <p className="font-sans text-sm text-outline dark:text-[rgba(250,247,242,0.5)]">
            Last updated: {LAST_UPDATED}
          </p>
        </div>

        <div className="space-y-8 font-sans text-sm text-on-surface-variant dark:text-[rgba(250,247,242,0.75)] leading-relaxed">

          <section>
            <h2 className="font-serif text-xl text-on-surface dark:text-[#FAF7F2] font-normal mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using WAYFARE ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-on-surface dark:text-[#FAF7F2] font-normal mb-3">2. Description of Service</h2>
            <p>WAYFARE is an AI-powered travel discovery and itinerary planning platform. The Service provides:</p>
            <ul className="space-y-1 list-disc list-inside mt-2">
              <li>AI-generated travel itineraries based on user-provided destination inputs</li>
              <li>Curated information about destinations, hotels, and activities</li>
              <li>Travel inspiration through photos and video content</li>
              <li>The ability to save and manage personal trip plans (registered users only)</li>
            </ul>
          </section>

          <section>
            <h2 className="font-serif text-xl text-on-surface dark:text-[#FAF7F2] font-normal mb-3">3. AI-Generated Content Disclaimer</h2>
            <p className="font-semibold text-on-surface dark:text-[#FAF7F2] mb-2">Important: AI-generated itineraries are suggestions only.</p>
            <ul className="space-y-2 list-disc list-inside">
              <li>Itineraries are generated by AI and may contain inaccuracies, outdated information, or errors.</li>
              <li>Opening hours, prices, and availability of places change. Always verify before travelling.</li>
              <li>WAYFARE is not responsible for any travel disruption, loss, or inconvenience arising from following AI-generated recommendations.</li>
              <li>We strongly recommend cross-referencing itineraries with official tourism boards and travel advisories.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-serif text-xl text-on-surface dark:text-[#FAF7F2] font-normal mb-3">4. User Accounts</h2>
            <ul className="space-y-2 list-disc list-inside">
              <li>You must be at least 13 years old to create an account.</li>
              <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
              <li>You may not use another person's account without their permission.</li>
              <li>You are responsible for all activity that occurs under your account.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-serif text-xl text-on-surface dark:text-[#FAF7F2] font-normal mb-3">5. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="space-y-2 list-disc list-inside mt-2">
              <li>Use the Service for any unlawful purpose or in violation of any regulations.</li>
              <li>Attempt to reverse engineer, scrape, or automate access to the Service in bulk.</li>
              <li>Upload or transmit any harmful, offensive, or infringing content.</li>
              <li>Attempt to circumvent rate limits or security measures.</li>
              <li>Misrepresent your identity or affiliation.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-serif text-xl text-on-surface dark:text-[#FAF7F2] font-normal mb-3">6. Third-Party Content & Links</h2>
            <p>WAYFARE displays content from third-party sources including Google Places, Pexels, and booking platforms. We are not responsible for the accuracy, availability, or policies of third-party content or websites linked from our Service.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-on-surface dark:text-[#FAF7F2] font-normal mb-3">7. Intellectual Property</h2>
            <p>All original content, design, and code comprising WAYFARE is the property of WAYFARE and its creators. You may not reproduce, distribute, or create derivative works without explicit written permission.</p>
            <p className="mt-2">Third-party images and videos displayed on the platform are subject to their respective licenses (Pexels, Google Places, Unsplash).</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-on-surface dark:text-[#FAF7F2] font-normal mb-3">8. Limitation of Liability</h2>
            <p>To the fullest extent permitted by law, WAYFARE and its creators shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including but not limited to travel losses, booking errors, or reliance on AI-generated content.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-on-surface dark:text-[#FAF7F2] font-normal mb-3">9. Modifications to Terms</h2>
            <p>We reserve the right to modify these Terms at any time. Continued use of the Service after changes constitutes acceptance of the revised Terms. We will notify registered users of significant changes via email.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-on-surface dark:text-[#FAF7F2] font-normal mb-3">10. Governing Law</h2>
            <p>These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts of India.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-on-surface dark:text-[#FAF7F2] font-normal mb-3">11. Contact</h2>
            <p>For any queries regarding these Terms: <a href={`mailto:${CONTACT_EMAIL}`} className="text-primary dark:text-[#1E8C80] underline">{CONTACT_EMAIL}</a></p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
