import { TripPlan, Place } from "./types";

export function generateDynamicFallbackPlan(
  locationName: string,
  durationDays: number = 3,
  tripStyle: string = "balanced",
  dietaryPref: string = "any"
): TripPlan {
  const cleanName = locationName.trim();
  const isIndia =
    cleanName.toLowerCase().includes("india") ||
    ["jaipur", "varanasi", "rishikesh", "ladakh", "alleppey", "goa", "mumbai", "delhi", "kerala", "hampi", "udaipur", "manali", "shimla", "agra"].some((c) =>
      cleanName.toLowerCase().includes(c)
    );

  const currency = isIndia ? "INR" : "USD";
  const minCost = isIndia ? 3500 * durationDays : 180 * durationDays;
  const maxCost = isIndia ? 7500 * durationDays : 340 * durationDays;

  // Generate city-appropriate mock places based on location name
  const cityLower = cleanName.toLowerCase();

  if (cityLower.includes("jaipur")) {
    return {
      id: `jaipur-plan-${Date.now()}`,
      title: "Royal Pink City Heritage & Haveli Retreat",
      location_name: "Jaipur, India",
      state_country: "Rajasthan, India",
      lat: 26.9124,
      lng: 75.7873,
      duration_days: durationDays,
      trip_style: tripStyle,
      dietary_pref: dietaryPref === "any" ? "satvik" : dietaryPref,
      travelers_count: 2,
      budget: {
        hotel_cost_min: 4200,
        hotel_cost_max: 9500,
        food_cost_min: 2200,
        food_cost_max: 4800,
        transport_cost_min: 1200,
        transport_cost_max: 2200,
        activities_cost_min: 1500,
        activities_cost_max: 3000,
        total_estimate_min: 9100,
        total_estimate_max: 19500,
        currency: "INR",
        is_estimate: true,
      },
      days: [
        {
          day_number: 1,
          theme_title: "Amber Fort Sunsets & Terracotta Havelis",
          description: "Explore the hilltop Amber Palace above Maota Lake, followed by artisanal block-print textile ateliers.",
          items: [
            {
              id: "jp-1",
              day_number: 1,
              time_slot: "morning",
              order_index: 1,
              suggested_duration_mins: 120,
              travel_notes: "Arrive at 08:30 AM to beat the mid-day heat. Ascend via the Sun Gate to inspect Sheesh Mahal mirror courtyard.",
              place: {
                id: "jp_amber",
                place_id: "ChIJ_amber_fort",
                name: "Amber Fort & Sheesh Mahal",
                category: "attraction",
                sub_category: "Royal Fort Complex",
                business_status: "OPERATIONAL",
                rating: 4.8,
                user_ratings_total: 45000,
                photo_url: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800",
                lat: 26.9855,
                lng: 75.8513,
                editorial_summary: "16th-century yellow and pink sandstone fortress commanding panoramic views over Maota Lake.",
              },
            },
            {
              id: "jp-2",
              day_number: 1,
              time_slot: "afternoon",
              order_index: 2,
              suggested_duration_mins: 60,
              travel_notes: "Photograph the water palace floating on Man Sagar Lake at golden hour.",
              place: {
                id: "jp_jalmahal",
                place_id: "ChIJ_jal_mahal",
                name: "Jal Mahal (Water Palace Pavilion)",
                category: "attraction",
                sub_category: "Historic Lake Pavilion",
                business_status: "OPERATIONAL",
                rating: 4.6,
                user_ratings_total: 28000,
                photo_url: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800",
                lat: 26.9534,
                lng: 75.8462,
                editorial_summary: "A Rajput-style architectural marvel appearing to float in the middle of Man Sagar Lake.",
              },
            },
            {
              id: "jp-3",
              day_number: 1,
              time_slot: "evening",
              order_index: 3,
              suggested_duration_mins: 90,
              travel_notes: "Enjoy authentic Rajasthani Dal Baati Churma and Ghevar served on brass thalis.",
              place: {
                id: "jp_lmb",
                place_id: "ChIJ_lmb_jaipur",
                name: "LMB Heritage Rajasthani Thali",
                category: "food",
                sub_category: "Pure Veg Culinary Heritage",
                business_status: "OPERATIONAL",
                rating: 4.7,
                user_ratings_total: 12500,
                veg_status: "pure_veg",
                photo_url: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800",
                lat: 26.9205,
                lng: 75.8236,
                editorial_summary: "18th-century legendary culinary establishment in Johari Bazaar famous for pure ghee sweets and royal thalis.",
              },
            },
          ],
        },
        {
          day_number: 2,
          theme_title: "City Palace & Royal Jantar Mantar",
          description: "Wander through the honeycomb facade of Hawa Mahal and the royal court yards of City Palace.",
          items: [
            {
              id: "jp-4",
              day_number: 2,
              time_slot: "morning",
              order_index: 1,
              suggested_duration_mins: 90,
              travel_notes: "Admire the 953 lattice windows designed for royal ladies to observe street processions unseen.",
              place: {
                id: "jp_hawamahal",
                place_id: "ChIJ_hawa_mahal",
                name: "Hawa Mahal (Palace of Winds)",
                category: "attraction",
                sub_category: "Royal Architecture",
                business_status: "OPERATIONAL",
                rating: 4.7,
                user_ratings_total: 62000,
                photo_url: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800",
                lat: 26.9239,
                lng: 75.8267,
                editorial_summary: "Iconic five-story pink sandstone structure built in 1799 in the shape of Lord Krishna's crown.",
              },
            },
            {
              id: "jp-5",
              day_number: 2,
              time_slot: "afternoon",
              order_index: 2,
              suggested_duration_mins: 75,
              travel_notes: "Inspect the peacock courtyard (Pritam Niwas Chowk) and royal armory museum.",
              place: {
                id: "jp_citypalace",
                place_id: "ChIJ_city_palace",
                name: "Jaipur City Palace & Chandra Mahal",
                category: "attraction",
                sub_category: "Royal Residence",
                business_status: "OPERATIONAL",
                rating: 4.8,
                user_ratings_total: 39000,
                photo_url: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800",
                lat: 26.9258,
                lng: 75.8237,
                editorial_summary: "Resplendent palace complex blending Rajasthani and Mughal architectural heritage, still housing the royal family.",
              },
            },
          ],
        },
      ],
      stays: [
        {
          id: "jp_stay_1",
          place_id: "rambagh_palace",
          name: "Rambagh Palace Heritage Resort",
          category: "stay",
          business_status: "OPERATIONAL",
          rating: 4.9,
          photo_url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
          lat: 26.898,
          lng: 75.808,
        },
      ],
    };
  }

  // Dynamic fallback for any custom location user searches for
  return {
    id: `plan-${Date.now()}`,
    title: `Contemplative Journey in ${cleanName}`,
    location_name: cleanName,
    state_country: isIndia ? `${cleanName}, India` : `${cleanName}`,
    lat: isIndia ? 26.9124 : 35.0116,
    lng: isIndia ? 75.7873 : 135.7681,
    duration_days: durationDays,
    trip_style: tripStyle,
    dietary_pref: dietaryPref,
    travelers_count: 2,
    budget: {
      hotel_cost_min: Math.round(minCost * 0.45),
      hotel_cost_max: Math.round(maxCost * 0.45),
      food_cost_min: Math.round(minCost * 0.25),
      food_cost_max: Math.round(maxCost * 0.25),
      transport_cost_min: Math.round(minCost * 0.15),
      transport_cost_max: Math.round(maxCost * 0.15),
      activities_cost_min: Math.round(minCost * 0.15),
      activities_cost_max: Math.round(maxCost * 0.15),
      total_estimate_min: minCost,
      total_estimate_max: maxCost,
      currency,
      is_estimate: true,
    },
    days: Array.from({ length: Math.min(durationDays, 4) }, (_, i) => ({
      day_number: i + 1,
      theme_title: i === 0 ? `Historic Heritage & Morning Promenade in ${cleanName}` : `Artisanal Corridors & Local Flavors in ${cleanName}`,
      description: `Hand-sequenced discovery of verified operational landmarks and local culinary sanctuaries across ${cleanName}.`,
      items: [
        {
          id: `dyn-${i}-1`,
          day_number: i + 1,
          time_slot: "morning",
          order_index: 1,
          suggested_duration_mins: 90,
          travel_notes: `Begin morning exploration at the historic promenade of ${cleanName} before crowds arrive.`,
          place: {
            id: `spot-${cleanName}-1`,
            place_id: `place_${cleanName}_1`,
            name: `${cleanName} Central Historic Plaza & Sanctuary`,
            category: "attraction",
            sub_category: "Heritage Monument",
            business_status: "OPERATIONAL",
            rating: 4.8,
            user_ratings_total: 3200,
            photo_url: isIndia
              ? "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800"
              : "https://images.unsplash.com/photo-1509840841025-9088ba78a826?w=800",
            lat: isIndia ? 26.9124 : 35.0116,
            lng: isIndia ? 75.7873 : 135.7681,
            editorial_summary: `The iconic architectural landmark of ${cleanName}, offering historic heritage and atmospheric morning walks.`,
          },
        },
        {
          id: `dyn-${i}-2`,
          day_number: i + 1,
          time_slot: "afternoon",
          order_index: 2,
          suggested_duration_mins: 60,
          travel_notes: `Enjoy authentic local cuisine and traditional tea/coffee delicacies.`,
          place: {
            id: `spot-${cleanName}-2`,
            place_id: `place_${cleanName}_2`,
            name: `${cleanName} Heritage Culinary Salon`,
            category: "food",
            sub_category: isIndia ? "Satvik & Pure Veg Gastronomy" : "Local Artisanal Cafe",
            business_status: "OPERATIONAL",
            rating: 4.7,
            user_ratings_total: 1800,
            veg_status: isIndia ? "pure_veg" : "veg_options",
            photo_url: isIndia
              ? "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800"
              : "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800",
            lat: isIndia ? 26.9124 : 75.7873,
            lng: isIndia ? 75.7873 : 135.7681,
            editorial_summary: `A celebrated local dining sanctuary in ${cleanName} serving regional dishes crafted with organic ingredients.`,
          },
        },
      ],
    })),
    stays: [
      {
        id: `stay-${cleanName}`,
        place_id: `stay_${cleanName}`,
        name: `${cleanName} Heritage Boutique Resort`,
        category: "stay",
        business_status: "OPERATIONAL",
        rating: 4.9,
        photo_url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
        lat: isIndia ? 26.9124 : 35.0116,
        lng: isIndia ? 75.7873 : 135.7681,
      },
    ],
  };
}

export const SAMPLE_TRIP_PLANS: Record<string, TripPlan> = {
  "Kyoto, Japan": {
    id: "kyoto-plan",
    title: "Autumn in Kansai",
    location_name: "Kyoto, Japan",
    state_country: "Kansai Region, Japan",
    lat: 35.0116,
    lng: 135.7681,
    duration_days: 3,
    trip_style: "balanced",
    dietary_pref: "any",
    travelers_count: 2,
    budget: {
      hotel_cost_min: 1200,
      hotel_cost_max: 1800,
      food_cost_min: 600,
      food_cost_max: 900,
      transport_cost_min: 200,
      transport_cost_max: 350,
      activities_cost_min: 250,
      activities_cost_max: 400,
      total_estimate_min: 2250,
      total_estimate_max: 3450,
      currency: "INR",
      is_estimate: true,
    },
    days: [
      {
        day_number: 1,
        theme_title: "Arashiyama Bamboo & River Morning",
        description: "Early bamboo forest paths, Zen rock gardens, and soba lunch along the Oi river.",
        items: [
          {
            id: "kyoto-1",
            day_number: 1,
            time_slot: "morning",
            order_index: 1,
            suggested_duration_mins: 90,
            travel_notes: "Wander the 14th-century Sogenchi Garden before tour groups arrive. Reflection of Mt. Arashiyama in central pond.",
            place: {
              id: "p1",
              place_id: "ChIJb_f1064JAWARWzD00r2fVxE",
              name: "Tenryu-ji Temple & Zen Gardens",
              category: "attraction",
              sub_category: "Zen Buddhist Temple",
              business_status: "OPERATIONAL",
              rating: 4.8,
              user_ratings_total: 8200,
              photo_url: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800",
              lat: 35.0158,
              lng: 135.6775,
              editorial_summary: "Head temple of the Tenryu-ji branch of Rinzai Zen Buddhism, celebrated for its 14th-century landscape garden.",
            },
          },
          {
            id: "kyoto-2",
            day_number: 1,
            time_slot: "afternoon",
            order_index: 2,
            suggested_duration_mins: 60,
            travel_notes: "Privately chartered pole-punt boat drifting upstream along the gorge with freshly brewed sencha.",
            place: {
              id: "p2",
              place_id: "ChIJd3P5oW4JAWAR6Z7Wk2Pz",
              name: "Oi River Private Wooden Boat Drift",
              category: "attraction",
              sub_category: "River Scenic Route",
              business_status: "OPERATIONAL",
              rating: 4.9,
              user_ratings_total: 1400,
              photo_url: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=800",
              lat: 35.0135,
              lng: 135.6772,
              editorial_summary: "A contemplative river journey along emerald forested cliffs on traditional wooden flatboats.",
            },
          },
        ],
      },
    ],
    stays: [
      {
        id: "s1",
        place_id: "stay_sowaka",
        name: "Sowaka Ryokan & Tea Pavilion",
        category: "stay",
        business_status: "OPERATIONAL",
        rating: 4.9,
        photo_url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800",
        lat: 35.0003,
        lng: 135.7788,
      },
    ],
  },
  "Varanasi, India": {
    id: "varanasi-plan",
    title: "Sacred Dawn on the Ganga",
    location_name: "Varanasi, India",
    state_country: "Uttar Pradesh, India",
    lat: 25.3176,
    lng: 82.9739,
    duration_days: 3,
    trip_style: "pilgrimage",
    dietary_pref: "pure_veg",
    travelers_count: 2,
    budget: {
      hotel_cost_min: 4500,
      hotel_cost_max: 9000,
      food_cost_min: 2500,
      food_cost_max: 4500,
      transport_cost_min: 1500,
      transport_cost_max: 2500,
      activities_cost_min: 2000,
      activities_cost_max: 3500,
      total_estimate_min: 10500,
      total_estimate_max: 19500,
      currency: "INR",
      is_estimate: true,
    },
    days: [
      {
        day_number: 1,
        theme_title: "Sunrise Rowing & Ancient Ghats",
        description: "Dawn wooden boat along Assi to Dashashwamedh Ghat, followed by labyrinthine lanes of Vishwanath Gali.",
        items: [
          {
            id: "v-1",
            day_number: 1,
            time_slot: "morning",
            order_index: 1,
            suggested_duration_mins: 120,
            travel_notes: "Board early (05:15 AM) at Assi Ghat to witness morning prayers and golden reflection on ancient stone facades.",
            place: {
              id: "v1",
              place_id: "ChIJassi_ghat_01",
              name: "Subah-e-Banaras & Assi Ghat Sunrise",
              category: "attraction",
              sub_category: "Sacred Ghat",
              business_status: "OPERATIONAL",
              rating: 4.9,
              user_ratings_total: 18500,
              photo_url: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800",
              lat: 25.2899,
              lng: 83.0069,
              editorial_summary: "The southern-most sacred ghat where Vedic hymns, morning raga, and yoga greet the first rays of the sun.",
            },
          },
          {
            id: "v-2",
            day_number: 1,
            time_slot: "evening",
            order_index: 2,
            suggested_duration_mins: 90,
            travel_notes: "Secure a vantage spot by 06:00 PM for the synchronized multi-priest brass lamp Aarti ceremony.",
            place: {
              id: "v3",
              place_id: "ChIJdashashwamedh_01",
              name: "Dashashwamedh Maha Ganga Aarti",
              category: "attraction",
              sub_category: "Spiritual Ritual",
              business_status: "OPERATIONAL",
              rating: 4.9,
              user_ratings_total: 32000,
              photo_url: "https://images.unsplash.com/photo-1571536802807-30451e3955d8?w=800",
              lat: 25.3075,
              lng: 83.0105,
              editorial_summary: "The most magnificent and spiritual spectacle in India, with illuminated tiered brass lamps and conch resonance.",
            },
          },
        ],
      },
    ],
    stays: [
      {
        id: "v-stay-1",
        place_id: "brijrama_palace",
        name: "BrijRama Palace Heritage Hotel",
        category: "stay",
        business_status: "OPERATIONAL",
        rating: 4.9,
        photo_url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
        lat: 25.308,
        lng: 83.011,
      },
    ],
  },
};

export function getOrCreateTripPlan(
  locationName: string,
  days: number = 3,
  style: string = "balanced",
  diet: string = "any"
): TripPlan {
  if (SAMPLE_TRIP_PLANS[locationName]) {
    return SAMPLE_TRIP_PLANS[locationName];
  }
  return generateDynamicFallbackPlan(locationName, days, style, diet);
}
